package com.tencent.wxcloudrun.dao;

import com.tencent.wxcloudrun.model.UserRecord;
import com.tencent.wxcloudrun.model.UserRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_record
     *
     * @mbg.generated Mon Mar 14 10:26:52 CST 2022
     */
    long countByExample(UserRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_record
     *
     * @mbg.generated Mon Mar 14 10:26:52 CST 2022
     */
    int deleteByExample(@Param("record") UserRecord record, @Param("example") UserRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_record
     *
     * @mbg.generated Mon Mar 14 10:26:52 CST 2022
     */
    int deleteByPrimaryKey(@Param("record") UserRecord record, @Param("id") Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_record
     *
     * @mbg.generated Mon Mar 14 10:26:52 CST 2022
     */
    int insert(UserRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_record
     *
     * @mbg.generated Mon Mar 14 10:26:52 CST 2022
     */
    int insertSelective(UserRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_record
     *
     * @mbg.generated Mon Mar 14 10:26:52 CST 2022
     */
    List<UserRecord> selectByExample(UserRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_record
     *
     * @mbg.generated Mon Mar 14 10:26:52 CST 2022
     */
    UserRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_record
     *
     * @mbg.generated Mon Mar 14 10:26:52 CST 2022
     */
    int updateByExampleSelective(@Param("record") UserRecord record, @Param("example") UserRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_record
     *
     * @mbg.generated Mon Mar 14 10:26:52 CST 2022
     */
    int updateByExample(@Param("record") UserRecord record, @Param("example") UserRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_record
     *
     * @mbg.generated Mon Mar 14 10:26:52 CST 2022
     */
    int updateByPrimaryKeySelective(UserRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_record
     *
     * @mbg.generated Mon Mar 14 10:26:52 CST 2022
     */
    int updateByPrimaryKey(UserRecord record);

    int insertBatch(List<UserRecord> records);

    int updateBatch(List<UserRecord> records);
}