package com.tencent.wxcloudrun.model;

import com.tencent.wxcloudrun.common.bean.BaseModel;
import com.tencent.wxcloudrun.util.Id;
import java.util.Date;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_record
 */
@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UserRecord extends BaseModel {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.id
     *
     * @mbg.generated Mon Mar 14 10:26:52 CST 2022
     */
    @Id(type = Id.Type.ID_WORKER)
    private Long id;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.create_time
     *
     * @mbg.generated Mon Mar 14 10:26:52 CST 2022
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.update_time
     *
     * @mbg.generated Mon Mar 14 10:26:52 CST 2022
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   用户对应AppID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.open_id
     *
     * @mbg.generated Mon Mar 14 10:26:52 CST 2022
     */
    private String openId;

    /**
     * Database Column Remarks:
     *   记录信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.record
     *
     * @mbg.generated Mon Mar 14 10:26:52 CST 2022
     */
    private String record;

    /**
     * Database Column Remarks:
     *   执行时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.execute_time
     *
     * @mbg.generated Mon Mar 14 10:26:52 CST 2022
     */
    private Date executeTime;

    /**
     * Database Column Remarks:
     *   是否删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.deleted
     *
     * @mbg.generated Mon Mar 14 10:26:52 CST 2022
     */
    private Long deleted;
}